name: Build & Deploy (Frontend)

on:
  workflow_dispatch:
  push:

jobs:
  build:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: "16"
        cache: "npm"
    - run: "npm install"

    - name: Build pages
      run: npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
